import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full bg-white dark:bg-gray-900">
          <div className="w-full mx-auto px-4">
            <div className="flex items-center h-16">
              {/* Left: Navigation Links */}
              <div className="flex flex-1 justify-start">
                <div className="flex items-center space-x-4">
                  <Link href="/" className="font-bold text-lg hover:underline">
                    Home
                  </Link>
                  <Link href="/crop-selection" className="hover:underline">
                    Crop Selection
                  </Link>
                  <Link href="/soil-management" className="hover:underline">
                    Soil Management
                  </Link>
                  <Link
                    href="/disease-identification"
                    className="hover:underline"
                  >
                    Disease Identification
                  </Link>
                  <Link href="/weather" className="hover:underline">
                    Weather
                  </Link>
                  <Link href="/community" className="hover:underline">
                    Community
                  </Link>
                  <Link href="/dashboard" className="hover:underline">
                    Dashboard
                  </Link>
                </div>
              </div>
              {/* Right: Auth Buttons */}
              <div className="flex items-center space-x-2 ml-4">
                <Link
                  href="/login"
                  className="px-3 py-1 rounded hover:bg-gray-100 dark:hover:bg-gray-800"
                >
                  Login
                </Link>
                <Link
                  href="/register"
                  className="px-3 py-1 rounded bg-blue-600 text-white hover:bg-blue-700"
                >
                  Register
                </Link>
              </div>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
